# This file is part of UMAPINFO Designer.
#
# UMAPINFO Designer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# UMAPINFO Designer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with UMAPINFO Designer.  If not, see <https://www.gnu.org/licenses/>.
#
# Copyright 2021 Jading Tsunami
from UMAPINFODesigner.structure import utypes

# Credit:
# https://github.com/nkmk/python-snippets/blob/3c58602bfb74f604a9d33ecac5a0ae6a8002fb63/notebook/dict_get_key_from_value.py#L31-L36
def key_from_value(d, val):
    keys = [k for k, v in d.items() if v == val]
    if keys:
        return keys[0]
    return None

"""List of all valid UMAPINFO keys."""
umapinfo_keys = [
    "levelname",
    "label",
    "levelpic",
    "next",
    "nextsecret",
    "skytexture",
    "music",
    "exitpic",
    "enterpic",
    "partime",
    "endgame",
    "endpic",
    "endbunny",
    "endcast",
    "nointermission",
    "intertext",
    "intertextsecret",
    "interbackdrop",
    "intermusic",
    "episode",
    "bossaction"
]

thing_types = {
    "BaronOfHell": "Baron Of Hell",
    "Fatso": "Mancubus",
    "Arachnotron": "Arachnotron",
    "Cyberdemon": "Cyberdemon",
    "SpiderMastermind": "Spider Mastermind",
    "DoomPlayer": "Doom Marine",
    "ZombieMan": "Former Human",
    "ShotgunGuy": "Former Human Sergeant (Shotgun guy)",
    "Archvile": "Arch-vile",
    "ArchvileFire": "Archvile Fire",
    "Revenant": "Revenant",
    "RevenantTracer": "Revenant Tracer",
    "RevenantTracerSmoke": "Revenant Tracer Smoke",
    "FatShot": "Mancubus Fireball",
    "ChaingunGuy": "Former Human Commando (Chaingun Guy)",
    "DoomImp": "Imp",
    "Demon": "Demon",
    "Spectre": "Spectre",
    "Cacodemon": "Cacodemon",
    "BaronBall": "Baron Fireball",
    "HellKnight": "Hell Knight",
    "LostSoul": "Lost Soul",
    "PainElemental": "Pain Elemental",
    "WolfensteinSS": "Wolfenstein SS",
    "CommanderKeen": "Commander Keen",
    "BossBrain": "Boss Brain",
    "BossEye": "Boss Cube Spawner",
    "BossTarget": "Boss Cube Target",
    "SpawnShot": "Boss Cube",
    "SpawnFire": "Boss Cube Fire",
    "ExplosiveBarrel": "Barrel (Explosive)",
    "DoomImpBall": "Imp Fireball",
    "CacodemonBall": "Cacodemon Fireball",
    "Rocket": "Rocket",
    "PlasmaBall": "Plasma Fire",
    "BFGBall": "BFG Ball",
    "ArachnotronPlasma": "Arachnotron Plasma",
    "BulletPuff": "Bullet Puff",
    "Blood": "Blood",
    "TeleportFog": "Teleport Fog",
    "ItemFog": "Item Fog",
    "TeleportDest": "Teleport Destination",
    "BFGExtra": "BFG Tracer Flash",
    "GreenArmor": "Green Armor",
    "BlueArmor": "Blue Armor",
    "HealthBonus": "Health Bonus",
    "ArmorBonus": "Armor Bonus",
    "BlueCard": "Blue Keycard",
    "RedCard": "Red Keycard",
    "YellowCard": "Yellow Keycard",
    "YellowSkull": "Yellow Skull Key",
    "RedSkull": "Red Skull Key",
    "BlueSkull": "Blue Skull Key",
    "Stimpack": "Stimpack",
    "Medikit": "Medikit",
    "Soulsphere": "Soulsphere",
    "InvulnerabilitySphere": "Invulnerability Sphere",
    "Berserk": "Berserk",
    "BlurSphere": "Partial Invisibility Sphere",
    "RadSuit": "Radiation Suit",
    "Allmap": "Computer Area Map",
    "Infrared": "Light-amplification Visor",
    "Megasphere": "Megasphere",
    "Clip": "Ammo Clip",
    "ClipBox": "Box of Ammo",
    "RocketAmmo": "Rocket Ammo",
    "RocketBox": "Box of Rockets",
    "Cell": "Energy Cell",
    "CellPack": "Energy Cell Pack",
    "Shell": "Shotgun Shells",
    "ShellBox": "Box of Shells",
    "Backpack": "Backpack",
    "BFG9000": "BFG9000",
    "Chaingun": "Chaingun",
    "Chainsaw": "Chainsaw",
    "RocketLauncher": "Rocket Launcher",
    "PlasmaRifle": "Plasma Rifle",
    "Shotgun": "Shotgun",
    "SuperShotgun": "Super Shotgun",
    "TechLamp": "Tech Lamp",
    "TechLamp2": "Tech Lamp 2",
    "Column": "Light Column",
    "TallGreenColumn": "Tall Green Column",
    "ShortGreenColumn": "Short Green Column",
    "TallRedColumn": "Tall Red Column",
    "ShortRedColumn": "Short Red Column",
    "SkullColumn": "Skull Column",
    "HeartColumn": "Heart Column",
    "EvilEye": "Evil Eye",
    "FloatingSkull": "Floating Skull",
    "TorchTree": "Torch Tree",
    "BlueTorch": "Blue Torch",
    "GreenTorch": "Green Torch",
    "RedTorch": "Red Torch",
    "ShortBlueTorch": "Short Blue Torch",
    "ShortGreenTorch": "Short Green Torch",
    "ShortRedTorch": "Short Red Torch",
    "Stalagtite": "Stalagtite",
    "TechPillar": "Tech Column",
    "CandleStick": "Candle",
    "Candelabra": "Candelabra",
    "BloodyTwitch": "Bloody Twitch",
    "Meat2": "Meat 2",
    "Meat3": "Meat 3",
    "Meat4": "Meat 4",
    "Meat5": "Meat 5",
    "NonsolidMeat2": "Nonsolid Meat 2",
    "NonsolidMeat4": "Nonsolid Meat 4",
    "NonsolidMeat3": "Nonsolid Meat 3",
    "NonsolidMeat5": "Nonsolid Meat 5",
    "NonsolidTwitch": "Nonsolid Twitch",
    "DeadCacodemon": "Dead Cacodemon",
    "DeadMarine": "Dead Doom Marine",
    "DeadZombieMan": "Dead Former Human",
    "DeadDemon": "Dead Demon",
    "DeadLostSoul": "Dead Lost Soul",
    "DeadDoomImp": "Dead Imp",
    "DeadShotgunGuy": "Dead Former Human Sergeant",
    "GibbedMarine": "Gibbed Doom Marine",
    "GibbedMarineExtra": "Gibbed Doom Marine 2",
    "HeadsOnAStick": "Heads on a Stick",
    "Gibs": "Gibs",
    "HeadOnAStick": "Head on a Stick",
    "HeadCandles": "Head Candles",
    "DeadStick": "Dead Stick",
    "LiveStick": "Live Stick",
    "BigTree": "Big Tree",
    "BurningBarrel": "Burning Barrel",
    "HangNoGuts": "Hang No Guts",
    "HangBNoBrain": "Hang Body (No Brain)",
    "HangTLookingDown": "Hanging T-Body Looking Down",
    "HangTSkull": "Hanging T-Body, Skull",
    "HangTLookingUp": "Hanging T-Body Looking Up",
    "HangTNoBrain": "Hanging T-Body No Brain",
    "ColonGibs": "Pool of Blod with Guts",
    "SmallBloodPool": "Small Blood Pool",
    "BrainStem": "Brain Stem",
    "PointPusher": "Point Pusher",
    "PointPuller": "Point Puller",
    "MBFHelperDog": "MBF Helper Dog",
    "PlasmaBall1": "Plasma Ball 1",
    "PlasmaBall2": "Plasma Ball 2",
    "EvilSceptre": "Evil Sceptre",
    "UnholyBible": "Unholy Bible",
    "MusicChanger": "Music Changer",
    "Deh_Actor_145": "Deh Actor 145",
    "Deh_Actor_146": "Deh Actor 146",
    "Deh_Actor_147": "Deh Actor 147",
    "Deh_Actor_148": "Deh Actor 148",
    "Deh_Actor_149": "Deh Actor 149",
    "Deh_Actor_150": "Deh Actor 150",
    "Deh_Actor_151": "Deh Actor 151",
    "Deh_Actor_152": "Deh Actor 152",
    "Deh_Actor_153": "Deh Actor 153",
    "Deh_Actor_154": "Deh Actor 154",
    "Deh_Actor_155": "Deh Actor 155",
    "Deh_Actor_156": "Deh Actor 156",
    "Deh_Actor_157": "Deh Actor 157",
    "Deh_Actor_158": "Deh Actor 158",
    "Deh_Actor_159": "Deh Actor 159",
    "Deh_Actor_160": "Deh Actor 160",
    "Deh_Actor_161": "Deh Actor 161",
    "Deh_Actor_162": "Deh Actor 162",
    "Deh_Actor_163": "Deh Actor 163",
    "Deh_Actor_164": "Deh Actor 164",
    "Deh_Actor_165": "Deh Actor 165",
    "Deh_Actor_166": "Deh Actor 166",
    "Deh_Actor_167": "Deh Actor 167",
    "Deh_Actor_168": "Deh Actor 168",
    "Deh_Actor_169": "Deh Actor 169",
    "Deh_Actor_170": "Deh Actor 170",
    "Deh_Actor_171": "Deh Actor 171",
    "Deh_Actor_172": "Deh Actor 172",
    "Deh_Actor_173": "Deh Actor 173",
    "Deh_Actor_174": "Deh Actor 174",
    "Deh_Actor_175": "Deh Actor 175",
    "Deh_Actor_176": "Deh Actor 176",
    "Deh_Actor_177": "Deh Actor 177",
    "Deh_Actor_178": "Deh Actor 178",
    "Deh_Actor_179": "Deh Actor 179",
    "Deh_Actor_180": "Deh Actor 180",
    "Deh_Actor_181": "Deh Actor 181",
    "Deh_Actor_182": "Deh Actor 182",
    "Deh_Actor_183": "Deh Actor 183",
    "Deh_Actor_184": "Deh Actor 184",
    "Deh_Actor_185": "Deh Actor 185",
    "Deh_Actor_186": "Deh Actor 186",
    "Deh_Actor_187": "Deh Actor 187",
    "Deh_Actor_188": "Deh Actor 188",
    "Deh_Actor_189": "Deh Actor 189",
    "Deh_Actor_190": "Deh Actor 190",
    "Deh_Actor_191": "Deh Actor 191",
    "Deh_Actor_192": "Deh Actor 192",
    "Deh_Actor_193": "Deh Actor 193",
    "Deh_Actor_194": "Deh Actor 194",
    "Deh_Actor_195": "Deh Actor 195",
    "Deh_Actor_196": "Deh Actor 196",
    "Deh_Actor_197": "Deh Actor 197",
    "Deh_Actor_198": "Deh Actor 198",
    "Deh_Actor_199": "Deh Actor 199",
    "Deh_Actor_200": "Deh Actor 200",
    "Deh_Actor_201": "Deh Actor 201",
    "Deh_Actor_202": "Deh Actor 202",
    "Deh_Actor_203": "Deh Actor 203",
    "Deh_Actor_204": "Deh Actor 204",
    "Deh_Actor_205": "Deh Actor 205",
    "Deh_Actor_206": "Deh Actor 206",
    "Deh_Actor_207": "Deh Actor 207",
    "Deh_Actor_208": "Deh Actor 208",
    "Deh_Actor_209": "Deh Actor 209",
    "Deh_Actor_210": "Deh Actor 210",
    "Deh_Actor_211": "Deh Actor 211",
    "Deh_Actor_212": "Deh Actor 212",
    "Deh_Actor_213": "Deh Actor 213",
    "Deh_Actor_214": "Deh Actor 214",
    "Deh_Actor_215": "Deh Actor 215",
    "Deh_Actor_216": "Deh Actor 216",
    "Deh_Actor_217": "Deh Actor 217",
    "Deh_Actor_218": "Deh Actor 218",
    "Deh_Actor_219": "Deh Actor 219",
    "Deh_Actor_220": "Deh Actor 220",
    "Deh_Actor_221": "Deh Actor 221",
    "Deh_Actor_222": "Deh Actor 222",
    "Deh_Actor_223": "Deh Actor 223",
    "Deh_Actor_224": "Deh Actor 224",
    "Deh_Actor_225": "Deh Actor 225",
    "Deh_Actor_226": "Deh Actor 226",
    "Deh_Actor_227": "Deh Actor 227",
    "Deh_Actor_228": "Deh Actor 228",
    "Deh_Actor_229": "Deh Actor 229",
    "Deh_Actor_230": "Deh Actor 230",
    "Deh_Actor_231": "Deh Actor 231",
    "Deh_Actor_232": "Deh Actor 232",
    "Deh_Actor_233": "Deh Actor 233",
    "Deh_Actor_234": "Deh Actor 234",
    "Deh_Actor_235": "Deh Actor 235",
    "Deh_Actor_236": "Deh Actor 236",
    "Deh_Actor_237": "Deh Actor 237",
    "Deh_Actor_238": "Deh Actor 238",
    "Deh_Actor_239": "Deh Actor 239",
    "Deh_Actor_240": "Deh Actor 240",
    "Deh_Actor_241": "Deh Actor 241",
    "Deh_Actor_242": "Deh Actor 242",
    "Deh_Actor_243": "Deh Actor 243",
    "Deh_Actor_244": "Deh Actor 244",
    "Deh_Actor_245": "Deh Actor 245",
    "Deh_Actor_246": "Deh Actor 246",
    "Deh_Actor_247": "Deh Actor 247",
    "Deh_Actor_248": "Deh Actor 248",
    "Deh_Actor_249": "Deh Actor 249"
}

supported_iwads = {
    "udoom.wad"    : utypes.IWADType.DOOM,
    "doom.wad"     : utypes.IWADType.DOOM,
    "heretic.wad"  : utypes.IWADType.DOOM,
    "freedoom.wad" : utypes.IWADType.DOOM,
    "freedoom2.wad": utypes.IWADType.DOOM2,
    "doom2.wad"    : utypes.IWADType.DOOM2,
    "doom2f.wad"   : utypes.IWADType.DOOM2,
    "tnt.wad"      : utypes.IWADType.DOOM2,
    "plutonia.wad" : utypes.IWADType.DOOM2,
    "hexen.wad"    : utypes.IWADType.DOOM2,
    "hexdd.wad"    : utypes.IWADType.DOOM2
}

# Linedef definitions courtesy of Doom Wiki:
# https://doomwiki.org/w/index.php?title=Linedef_type&oldid=266105
# Licensed under CC BY-SA 4.0 (compatible with GPLv3)

crossable_specials = {
    2  :    "W1 Door Stay Open",
    3  :    "W1 Door Close",
    4  :    "W1 Door",
    5  :    "W1 Floor To Lowest Adjacent Ceiling",
    6  :    "W1 Start Crusher, Fast Damage",
    8  :    "W1 Build Stairs 8 Up",
    10 :    "W1 Lift Also Monsters",
    12 :    "W1 Light To Highest Adjacent Level",
    13 :    "W1 Light To 255",
    16 :    "W1 Door Close and Open",
    17 :    "W1 Light Blink 1.0 Sec",
    19 :    "W1 Floor To Highest Adjacent Floor",
    22 :    "W1 Floor To Higher Floor Change Texture",
    25 :    "W1 Start Crusher, Slow Damage",
    30 :    "W1 Floor Up Shortest Lower Texture",
    35 :    "W1 Light To 35",
    36 :    "W1 Floor To 8 Above Highest Adjacent Floor Fast",
    37 :    "W1 Floor To Lowest Adjacent Floor Change Texture and Type",
    38 :    "W1 Floor To Lowest Adjacent Floor",
    40 :    "W1 Ceiling To Highest Ceiling",
    44 :    "W1 Ceiling To 8 Above Floor",
    52 :    "W1 Exit (Normal)",
    53 :    "W1 Start Moving Floor",
    54 :    "W1 Stop Moving Floor",
    56 :    "W1 Floor To 8 Below Lowest Adjacent Ceiling and Crush",
    57 :    "W1 Stop Crusher",
    58 :    "W1 Floor Up 24",
    59 :    "W1 Floor Up 24 Change Texture and Type",
    72 :    "WR Ceiling To 8 Above Floor",
    73 :    "WR Start Crusher, Slow Damage",
    74 :    "WR Stop Crusher",
    75 :    "WR Door Close",
    76 :    "WR Door Close and Open",
    77 :    "WR Start Crusher, Fast Damage",
    79 :    "WR Light To 35",
    80 :    "WR Light To Highest Adjacent Level",
    81 :    "WR Light To 255",
    82 :    "WR Floor To Lowest Adjacent Floor",
    83 :    "WR Floor To Highest Adjacent Floor",
    84 :    "WR Floor To Lowest Adjacent Floor Change Texture and Type",
    86 :    "WR Door Stay Open",
    87 :    "WR Start Moving Floor",
    88 :    "WR Lift Also Monsters",
    89 :    "WR Stop Moving Floor",
    90 :    "WR Door",
    91 :    "WR Floor To Lowest Adjacent Ceiling",
    92 :    "WR Floor Up 24",
    93 :    "WR Floor Up 24 Change Texture and Type",
    94 :    "WR Floor To 8 Below Lowest Adjacent Ceiling and Crush",
    95 :    "WR Floor To Higher Floor Change Texture",
    96 :    "WR Floor Up Shortest Lower Texture",
    98 :    "WR Floor To 8 Above Highest Adjacent Floor Fast",
    100:    "W1 Build Stairs 16 and Crush",
    104:    "W1 Light To Lowest Adjacent Level",
    105:    "WR Door Fast",
    106:    "WR Door Stay Open Fast",
    107:    "WR Door Close Fast",
    108:    "W1 Door Fast",
    109:    "W1 Door Stay Open Fast",
    110:    "W1 Door Close Fast",
    119:    "W1 Floor To Higher Adjacent Floor",
    120:    "WR Lift Fast",
    121:    "W1 Lift Fast",
    124:    "W1 Exit (Secret)",
    128:    "WR Floor To Higher Adjacent Floor",
    129:    "WR Floor To Higher Floor Fast",
    130:    "W1 Floor To Higher Floor Fast",
    141:    "W1 Start Crusher, Silent",
    142:    "W1 Floor Up 512",
    143:    "W1 Lift Up 24 Change Texture",
    144:    "W1 Lift Up 24 Remove Type",
    145:    "W1 Ceiling Down To Floor Fast",
    146:    "W1 Floor Donut Raise",
    147:    "WR Floor Up 512",
    148:    "WR Lift Up 24 Change Texture",
    149:    "WR Lift Up 24 Remove Type",
    150:    "WR Start Crusher Silent",
    151:    "WR Ceiling Up To Highest Ceiling",
    152:    "WR Ceiling Down To Floor Fast",
    153:    "W1 Change Floor Texture and Type (Trigger Model)",
    154:    "WR Change Floor Texture and Type (Trigger Model)",
    155:    "WR Floor Donut Raise",
    156:    "WR Light Start Blinking",
    157:    "WR Light To Lowest Adjacent Level",
    199:    "W1 Ceiling Down To Lowest Ceiling",
    200:    "W1 Ceiling Down To Highest Floor",
    201:    "WR Ceiling Down To Lowest Ceiling",
    202:    "WR Ceiling Down To Highest Floor",
    212:    "WR Toggle Floor To Ceiling (Instant)",
    219:    "W1 Floor Down To Adjacent Floor",
    220:    "WR Floor Down To Adjacent Floor",
    227:    "W1 Elevator To Higher Floor",
    228:    "WR Elevator To Higher Floor",
    231:    "W1 Elevator To Lower Floor",
    232:    "WR Elevator To Lower Floor",
    235:    "W1 Elevator To Current Floor",
    236:    "WR Elevator To Current Floor",
    239:    "W1 Change Floor Texture and Type (Numeric Model)",
    240:    "WR Change Floor Texture and Type (Numeric Model)",
    256:    "WR Build Stairs 8",
    257:    "WR Build Stairs 16 + Crush",
}

usable_specials = {
    11 :    "S1 Exit (Normal)",
    51 :    "S1 Exit (Secret)",
    60 :    "SR Floor To Lowest Adjacent Floor",
    61 :    "SR Door Stay Open",
    115:    "SR Door Stay Open Fast",
    7  :    "S1 Build Stairs 8 Up",
    9  :    "S1 Floor Donut",
    14 :    "S1 Floor Up 32 Change Texture",
    15 :    "S1 Floor Up 24 Change Texture",
    18 :    "S1 Floor To Higher Adjacent Floor",
    20 :    "S1 Floor To Higher Floor Change Texture",
    21 :    "S1 Lift",
    23 :    "S1 Floor To Lowest Adjacent Floor",
    29 :    "S1 Door",
    41 :    "S1 Ceiling To Floor",
    42 :    "SR Door Close",
    43 :    "SR Ceiling To Floor",
    45 :    "SR Floor To Highest Adjacent Floor",
    48 :    "Scrolling Wall Left",
    49 :    "S1 Start Crusher, Slow Damage",
    50 :    "S1 Door Close",
    55 :    "S1 Floor To 8 Below Lowest Adjacent Ceiling and Crush",
    62 :    "SR Lift",
    63 :    "SR Door",
    64 :    "SR Floor To Lowest Adjacent Ceiling",
    65 :    "SR Floor To 8 Below Lowest Adjacent Ceiling and Crush",
    66 :    "SR Floor Up 24 Change Texture",
    67 :    "SR Floor Up 32 Change Texture",
    68 :    "SR Floor To Higher Floor Change Texture",
    69 :    "SR Floor To Higher Adjacent Floor",
    70 :    "SR Floor To 8 Above Higher Adjacent Floor Fast",
    71 :    "S1 Floor To 8 Above Higher Adjacent Floor Fast",
    78 :    "SR Change Floor Texture and Type (Numeric Model)",
    101:    "S1 Floor To Lowest Adjacent Ceiling",
    102:    "S1 Floor To Highest Adjacent Floor",
    103:    "S1 Door Stay Open",
    111:    "S1 Door Fast",
    112:    "S1 Door Stay Open Fast",
    113:    "S1 Door Close Fast",
    114:    "SR Door Fast",
    116:    "SR Door Close Fast",
    122:    "S1 Lift Fast",
    123:    "SR Lift Fast",
    127:    "S1 Build Stairs 16 + Crush",
    131:    "S1 Floor To Higher Floor Fast",
    132:    "SR Floor To Higher Floor Fast",
    138:    "SR Light To 255",
    139:    "SR Light To 35",
    140:    "S1 Floor Up 512",
    158:    "S1 Floor Up By Shortest Lower Tex",
    159:    "S1 Floor To Lowest Adjacent Floor",
    160:    "S1 Floor Up 24 Change Texture and Type",
    161:    "S1 Floor Up 24",
    162:    "S1 Lift Perpetual",
    163:    "S1 Lift Stop",
    164:    "S1 Start Crusher, Fast Damage",
    165:    "S1 Start Crusher Silent",
    166:    "S1 Ceiling Up To Highest Ceiling",
    167:    "S1 Ceiling Down To 8 Above Floor",
    168:    "S1 Stop Crusher",
    169:    "S1 Light To Highest Adjacent Level",
    170:    "S1 Light To 35",
    171:    "S1 Light To 255",
    172:    "S1 Light Start Blinking",
    173:    "S1 Light To Lowest Adjacent Level",
    175:    "S1 Door Close and Open",
    176:    "SR Floor Up By Shortest Lower Texture",
    177:    "SR Floor To Lowest Adjacent Floor",
    178:    "SR Floor Up 512",
    179:    "SR Floor Up 24 Change Texture and Type",
    180:    "SR Floor Up 24",
    181:    "SR Lift Perpetual",
    182:    "SR Lift Stop",
    183:    "SR Start Crusher, Fast Damage",
    184:    "SR Start Crusher",
    185:    "SR Start Crusher Silent",
    186:    "SR Ceiling Up To Highest Ceiling",
    187:    "SR Ceiling Down To 8 Above Floor",
    188:    "SR Stop Crusher",
    189:    "S1 Change Floor Texture and Type (Trigger Model)",
    190:    "SR Change Floor Texture and Type (Trigger Model)",
    191:    "SR Floor Donut Raise",
    192:    "SR Light To Highest Adjacent Level",
    193:    "SR Light Start Blinking",
    194:    "SR Light To Lowest Adjacent Level",
    196:    "SR Door Close then Open",
    203:    "S1 Ceiling Down To Lowest Ceiling",
    204:    "S1 Ceiling Down To Highest Floor",
    205:    "SR Ceiling Down To Lowest Ceiling",
    206:    "SR Ceiling Down To Highest Floor",
    211:    "SR Toggle Floor To Ceiling (Instant)",
    221:    "S1 Floor Down To Adjacent Floor",
    222:    "SR Floor Down To Adjacent Floor",
    229:    "S1 Elevator To Higher Floor",
    230:    "SR Elevator To Higher Floor",
    233:    "S1 Elevator To Lower Floor",
    234:    "SR Elevator To Lower Floor",
    237:    "S1 Elevator To Current Floor",
    238:    "SR Elevator To Current Floor",
    241:    "S1 Change Floor Texture and Type (Numeric Model)",
    258:    "SR Build Stairs 8",
    259:    "SR Build Stairs 16 + Crush",
}
